# Generated by Django 6.0.3 on 2026-04-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=150)),
                ('anio', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('ciencia_ficcion', 'Ciencia Ficción'), ('animacion', 'Animación'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('documental', 'Documental'), ('otro', 'Otro')], max_length=50)),
                ('sinopsis', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-anio'],
            },
        ),
    ]
